"""empty message

Revision ID: 040207b0629e
Revises: ca9d7197d4d3
Create Date: 2019-11-22 13:26:31.014371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040207b0629e'
down_revision = 'ca9d7197d4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'ticket_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('events', 'event_place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_place', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('events', 'ticket_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
