"""empty message

Revision ID: 2bccda63df77
Revises: 040207b0629e
Create Date: 2019-11-22 14:17:18.215081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bccda63df77'
down_revision = '040207b0629e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_description', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'event_description')
    # ### end Alembic commands ###
