"""empty message

Revision ID: ca9d7197d4d3
Revises: 
Create Date: 2019-11-22 12:39:49.439285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9d7197d4d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_banner', sa.String(), nullable=True))
    op.add_column('events', sa.Column('event_place', sa.String(), nullable=False))
    op.add_column('events', sa.Column('event_time', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('ticket_price', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['id'])
    op.drop_column('events', 'time_event')
    op.drop_column('events', 'event_address_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_address_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('time_event', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'user_id')
    op.drop_column('events', 'ticket_price')
    op.drop_column('events', 'event_time')
    op.drop_column('events', 'event_place')
    op.drop_column('events', 'event_banner')
    # ### end Alembic commands ###
